baseURL = 'https://sakuramamoorthy.com/'
title = "Saku's Blog"
theme = 'ananke'
languageCode = "en-us"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "Saku's Blog"
    weight = 1
    contentDir = "content"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = ""
  favicon = "/images/blog-favicon-16x16.png"
  site_logo = ""
  description = "Welcome to Saku's Blog."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  recent_posts_number = 9
  disable_share = true

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/saku-ramamoorthy/"